# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/account_contract.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core import Tron_pb2 as core_dot_Tron__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core/contract/account_contract.proto',
  package='protocol',
  syntax='proto3',
  serialized_options=_b('\n\030org.tron.protos.contractZ)github.com/tronprotocol/grpc-gateway/core'),
  serialized_pb=_b('\n$core/contract/account_contract.proto\x12\x08protocol\x1a\x0f\x63ore/Tron.proto\"l\n\x15\x41\x63\x63ountCreateContract\x12\x15\n\rowner_address\x18\x01 \x01(\x0c\x12\x17\n\x0f\x61\x63\x63ount_address\x18\x02 \x01(\x0c\x12#\n\x04type\x18\x03 \x01(\x0e\x32\x15.protocol.AccountType\"D\n\x15\x41\x63\x63ountUpdateContract\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\x0c\x12\x15\n\rowner_address\x18\x02 \x01(\x0c\"A\n\x14SetAccountIdContract\x12\x12\n\naccount_id\x18\x01 \x01(\x0c\x12\x15\n\rowner_address\x18\x02 \x01(\x0c\"\xab\x01\n\x1f\x41\x63\x63ountPermissionUpdateContract\x12\x15\n\rowner_address\x18\x01 \x01(\x0c\x12#\n\x05owner\x18\x02 \x01(\x0b\x32\x14.protocol.Permission\x12%\n\x07witness\x18\x03 \x01(\x0b\x32\x14.protocol.Permission\x12%\n\x07\x61\x63tives\x18\x04 \x03(\x0b\x32\x14.protocol.PermissionBE\n\x18org.tron.protos.contractZ)github.com/tronprotocol/grpc-gateway/coreb\x06proto3')
  ,
  dependencies=[core_dot_Tron__pb2.DESCRIPTOR,])




_ACCOUNTCREATECONTRACT = _descriptor.Descriptor(
  name='AccountCreateContract',
  full_name='protocol.AccountCreateContract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner_address', full_name='protocol.AccountCreateContract.owner_address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_address', full_name='protocol.AccountCreateContract.account_address', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='protocol.AccountCreateContract.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=175,
)


_ACCOUNTUPDATECONTRACT = _descriptor.Descriptor(
  name='AccountUpdateContract',
  full_name='protocol.AccountUpdateContract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_name', full_name='protocol.AccountUpdateContract.account_name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner_address', full_name='protocol.AccountUpdateContract.owner_address', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=245,
)


_SETACCOUNTIDCONTRACT = _descriptor.Descriptor(
  name='SetAccountIdContract',
  full_name='protocol.SetAccountIdContract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='protocol.SetAccountIdContract.account_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner_address', full_name='protocol.SetAccountIdContract.owner_address', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=312,
)


_ACCOUNTPERMISSIONUPDATECONTRACT = _descriptor.Descriptor(
  name='AccountPermissionUpdateContract',
  full_name='protocol.AccountPermissionUpdateContract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner_address', full_name='protocol.AccountPermissionUpdateContract.owner_address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='protocol.AccountPermissionUpdateContract.owner', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='witness', full_name='protocol.AccountPermissionUpdateContract.witness', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actives', full_name='protocol.AccountPermissionUpdateContract.actives', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=486,
)

_ACCOUNTCREATECONTRACT.fields_by_name['type'].enum_type = core_dot_Tron__pb2._ACCOUNTTYPE
_ACCOUNTPERMISSIONUPDATECONTRACT.fields_by_name['owner'].message_type = core_dot_Tron__pb2._PERMISSION
_ACCOUNTPERMISSIONUPDATECONTRACT.fields_by_name['witness'].message_type = core_dot_Tron__pb2._PERMISSION
_ACCOUNTPERMISSIONUPDATECONTRACT.fields_by_name['actives'].message_type = core_dot_Tron__pb2._PERMISSION
DESCRIPTOR.message_types_by_name['AccountCreateContract'] = _ACCOUNTCREATECONTRACT
DESCRIPTOR.message_types_by_name['AccountUpdateContract'] = _ACCOUNTUPDATECONTRACT
DESCRIPTOR.message_types_by_name['SetAccountIdContract'] = _SETACCOUNTIDCONTRACT
DESCRIPTOR.message_types_by_name['AccountPermissionUpdateContract'] = _ACCOUNTPERMISSIONUPDATECONTRACT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountCreateContract = _reflection.GeneratedProtocolMessageType('AccountCreateContract', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTCREATECONTRACT,
  __module__ = 'core.contract.account_contract_pb2'
  # @@protoc_insertion_point(class_scope:protocol.AccountCreateContract)
  ))
_sym_db.RegisterMessage(AccountCreateContract)

AccountUpdateContract = _reflection.GeneratedProtocolMessageType('AccountUpdateContract', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTUPDATECONTRACT,
  __module__ = 'core.contract.account_contract_pb2'
  # @@protoc_insertion_point(class_scope:protocol.AccountUpdateContract)
  ))
_sym_db.RegisterMessage(AccountUpdateContract)

SetAccountIdContract = _reflection.GeneratedProtocolMessageType('SetAccountIdContract', (_message.Message,), dict(
  DESCRIPTOR = _SETACCOUNTIDCONTRACT,
  __module__ = 'core.contract.account_contract_pb2'
  # @@protoc_insertion_point(class_scope:protocol.SetAccountIdContract)
  ))
_sym_db.RegisterMessage(SetAccountIdContract)

AccountPermissionUpdateContract = _reflection.GeneratedProtocolMessageType('AccountPermissionUpdateContract', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTPERMISSIONUPDATECONTRACT,
  __module__ = 'core.contract.account_contract_pb2'
  # @@protoc_insertion_point(class_scope:protocol.AccountPermissionUpdateContract)
  ))
_sym_db.RegisterMessage(AccountPermissionUpdateContract)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
