# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/proposal_contract.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='core/contract/proposal_contract.proto',
  package='protocol',
  syntax='proto3',
  serialized_options=_b('\n\030org.tron.protos.contractZ)github.com/tronprotocol/grpc-gateway/core'),
  serialized_pb=_b('\n%core/contract/proposal_contract.proto\x12\x08protocol\"^\n\x17ProposalApproveContract\x12\x15\n\rowner_address\x18\x01 \x01(\x0c\x12\x13\n\x0bproposal_id\x18\x02 \x01(\x03\x12\x17\n\x0fis_add_approval\x18\x03 \x01(\x08\"\xa8\x01\n\x16ProposalCreateContract\x12\x15\n\rowner_address\x18\x01 \x01(\x0c\x12\x44\n\nparameters\x18\x02 \x03(\x0b\x32\x30.protocol.ProposalCreateContract.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\"D\n\x16ProposalDeleteContract\x12\x15\n\rowner_address\x18\x01 \x01(\x0c\x12\x13\n\x0bproposal_id\x18\x02 \x01(\x03\x42\x45\n\x18org.tron.protos.contractZ)github.com/tronprotocol/grpc-gateway/coreb\x06proto3')
)




_PROPOSALAPPROVECONTRACT = _descriptor.Descriptor(
  name='ProposalApproveContract',
  full_name='protocol.ProposalApproveContract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner_address', full_name='protocol.ProposalApproveContract.owner_address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proposal_id', full_name='protocol.ProposalApproveContract.proposal_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_add_approval', full_name='protocol.ProposalApproveContract.is_add_approval', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=145,
)


_PROPOSALCREATECONTRACT_PARAMETERSENTRY = _descriptor.Descriptor(
  name='ParametersEntry',
  full_name='protocol.ProposalCreateContract.ParametersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='protocol.ProposalCreateContract.ParametersEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='protocol.ProposalCreateContract.ParametersEntry.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=316,
)

_PROPOSALCREATECONTRACT = _descriptor.Descriptor(
  name='ProposalCreateContract',
  full_name='protocol.ProposalCreateContract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner_address', full_name='protocol.ProposalCreateContract.owner_address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='protocol.ProposalCreateContract.parameters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROPOSALCREATECONTRACT_PARAMETERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=316,
)


_PROPOSALDELETECONTRACT = _descriptor.Descriptor(
  name='ProposalDeleteContract',
  full_name='protocol.ProposalDeleteContract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner_address', full_name='protocol.ProposalDeleteContract.owner_address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proposal_id', full_name='protocol.ProposalDeleteContract.proposal_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=386,
)

_PROPOSALCREATECONTRACT_PARAMETERSENTRY.containing_type = _PROPOSALCREATECONTRACT
_PROPOSALCREATECONTRACT.fields_by_name['parameters'].message_type = _PROPOSALCREATECONTRACT_PARAMETERSENTRY
DESCRIPTOR.message_types_by_name['ProposalApproveContract'] = _PROPOSALAPPROVECONTRACT
DESCRIPTOR.message_types_by_name['ProposalCreateContract'] = _PROPOSALCREATECONTRACT
DESCRIPTOR.message_types_by_name['ProposalDeleteContract'] = _PROPOSALDELETECONTRACT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProposalApproveContract = _reflection.GeneratedProtocolMessageType('ProposalApproveContract', (_message.Message,), dict(
  DESCRIPTOR = _PROPOSALAPPROVECONTRACT,
  __module__ = 'core.contract.proposal_contract_pb2'
  # @@protoc_insertion_point(class_scope:protocol.ProposalApproveContract)
  ))
_sym_db.RegisterMessage(ProposalApproveContract)

ProposalCreateContract = _reflection.GeneratedProtocolMessageType('ProposalCreateContract', (_message.Message,), dict(

  ParametersEntry = _reflection.GeneratedProtocolMessageType('ParametersEntry', (_message.Message,), dict(
    DESCRIPTOR = _PROPOSALCREATECONTRACT_PARAMETERSENTRY,
    __module__ = 'core.contract.proposal_contract_pb2'
    # @@protoc_insertion_point(class_scope:protocol.ProposalCreateContract.ParametersEntry)
    ))
  ,
  DESCRIPTOR = _PROPOSALCREATECONTRACT,
  __module__ = 'core.contract.proposal_contract_pb2'
  # @@protoc_insertion_point(class_scope:protocol.ProposalCreateContract)
  ))
_sym_db.RegisterMessage(ProposalCreateContract)
_sym_db.RegisterMessage(ProposalCreateContract.ParametersEntry)

ProposalDeleteContract = _reflection.GeneratedProtocolMessageType('ProposalDeleteContract', (_message.Message,), dict(
  DESCRIPTOR = _PROPOSALDELETECONTRACT,
  __module__ = 'core.contract.proposal_contract_pb2'
  # @@protoc_insertion_point(class_scope:protocol.ProposalDeleteContract)
  ))
_sym_db.RegisterMessage(ProposalDeleteContract)


DESCRIPTOR._options = None
_PROPOSALCREATECONTRACT_PARAMETERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
