select count(1) from ext_error_block_num;
select count(1) from ext_block;
select count(1) from ext_trans;
select count(1) from ext_trans_market_order_detail;
select count(1) from ext_trans_auths;
select count(1) from ext_account_create_contract;
select count(1) from ext_transfer_contract;
select count(1) from ext_transfer_asset_contract;
select count(1) from ext_vote_asset_contract;
select count(1) from ext_vote_witness_contract;
select count(1) from ext_witness_create_contract;
select count(1) from ext_asset_issue_contract;
select count(1) from ext_asset_issue_contract_frozen_supply;
select count(1) from ext_witness_update_contract;
select count(1) from ext_participate_asset_issue_contract;
select count(1) from ext_account_update_contract;
select count(1) from ext_freeze_balance_contract;
select count(1) from ext_unfreeze_balance_contract;
select count(1) from ext_withdraw_balance_contract;
select count(1) from ext_unfreeze_asset_contract;
select count(1) from ext_update_asset_contract;
select count(1) from ext_proposal_create_contract;
select count(1) from ext_proposal_approve_contract;
select count(1) from ext_proposal_delete_contract;
select count(1) from ext_set_account_id_contract;
select count(1) from ext_trigger_smart_contract;
select count(1) from ext_update_setting_contract;
select count(1) from ext_exchange_create_contract;
select count(1) from ext_exchange_inject_contract;
select count(1) from ext_exchange_withdraw_contract;
select count(1) from ext_exchange_transaction_contract;
select count(1) from ext_update_energy_limit_contract;
select count(1) from ext_account_permission_update_contract;
select count(1) from ext_clear_abi_contract;
select count(1) from ext_update_brokerage_contract;
select count(1) from ext_shielded_transfer_contract;


drop table if exists  error_block_num;
drop table if exists  block;
drop table if exists  trans;
drop table if exists  trans_market_order_detail;
drop table if exists  trans_auths;
drop table if exists  account_create_contract;
drop table if exists  transfer_contract;
drop table if exists  transfer_asset_contract;                                                                                                     
drop table if exists  vote_asset_contract;
drop table if exists  vote_witness_contract;
drop table if exists  witness_create_contract;
drop table if exists  asset_issue_contract;
drop table if exists  asset_issue_contract_frozen_supply;
drop table if exists  witness_update_contract;
drop table if exists  participate_asset_issue_contract;
drop table if exists  account_update_contract;
drop table if exists  freeze_balance_contract;
drop table if exists  unfreeze_balance_contract;
drop table if exists  withdraw_balance_contract;
drop table if exists  unfreeze_asset_contract;
drop table if exists  update_asset_contract;
drop table if exists  proposal_create_contract;
drop table if exists  proposal_approve_contract;
drop table if exists  proposal_delete_contract;
drop table if exists  set_account_id_contract;
drop table if exists  trigger_smart_contract;
drop table if exists  update_setting_contract;
drop table if exists  exchange_create_contract;
drop table if exists  exchange_inject_contract;
drop table if exists  exchange_withdraw_contract;
drop table if exists  exchange_transaction_contract;
drop table if exists  update_energy_limit_contract;
drop table if exists  account_permission_update_contract;
drop table if exists  clear_abi_contract;
drop table if exists  update_brokerage_contract;
drop table if exists  shielded_transfer_contract;

insert into error_block_num select * from ext_error_block_num;
insert into block select * from ext_block;
insert into trans select * from ext_trans;
insert into trans_market_order_detail select * from ext_trans_market_order_detail;
insert into trans_auths select * from ext_trans_auths;
insert into account_create_contract select * from ext_account_create_contract;
insert into transfer_contract select * from ext_transfer_contract;
insert into transfer_asset_contract select * from ext_transfer_asset_contract;
insert into vote_witness_contract select * from ext_vote_witness_contract;
insert into witness_create_contract select * from ext_witness_create_contract;
insert into asset_issue_contract select * from ext_asset_issue_contract;
insert into asset_issue_contract_frozen_supply select * from ext_asset_issue_contract_frozen_supply;
insert into witness_update_contract select * from ext_witness_update_contract;
insert into participate_asset_issue_contract select * from ext_participate_asset_issue_contract;
insert into account_update_contract select * from ext_account_update_contract;
insert into freeze_balance_contract select * from ext_freeze_balance_contract;
insert into unfreeze_balance_contract select * from ext_unfreeze_balance_contract;
insert into withdraw_balance_contract select * from ext_withdraw_balance_contract;
insert into unfreeze_asset_contract select * from ext_unfreeze_asset_contract;
insert into update_asset_contract select * from ext_update_asset_contract;
insert into proposal_create_contract select * from ext_proposal_create_contract;
insert into proposal_approve_contract select * from ext_proposal_approve_contract;
insert into proposal_delete_contract select * from ext_proposal_delete_contract;
insert into set_account_id_contract select * from ext_set_account_id_contract;
insert into trigger_smart_contract select * from ext_trigger_smart_contract;
insert into update_setting_contract select * from ext_update_setting_contract;
insert into exchange_create_contract select * from ext_exchange_create_contract;
insert into exchange_inject_contract select * from ext_exchange_inject_contract;
insert into exchange_withdraw_contract select * from ext_exchange_withdraw_contract;
insert into exchange_transaction_contract select * from ext_exchange_transaction_contract;
insert into update_energy_limit_contract select * from ext_update_energy_limit_contract;
insert into account_permission_update_contract select * from ext_account_permission_update_contract;
insert into clear_abi_contract select * from ext_clear_abi_contract;
insert into update_brokerage_contract select * from ext_update_brokerage_contract;
insert into shielded_transfer_contract select * from ext_shielded_transfer_contract;



select count(1) from error_block_num;
select count(1) from block;
select count(1) from trans;
select count(1) from trans_market_order_detail;
select count(1) from trans_auths;
select count(1) from account_create_contract;
select count(1) from transfer_contract;
select count(1) from transfer_asset_contract;                                                                                           
select count(1) from vote_asset_contract;
select count(1) from vote_witness_contract;
select count(1) from witness_create_contract;
select count(1) from asset_issue_contract;
select count(1) from asset_issue_contract_frozen_supply;
select count(1) from witness_update_contract;
select count(1) from participate_asset_issue_contract;
select count(1) from account_update_contract;
select count(1) from freeze_balance_contract;
select count(1) from unfreeze_balance_contract;
select count(1) from withdraw_balance_contract;
select count(1) from unfreeze_asset_contract;
select count(1) from update_asset_contract;
select count(1) from proposal_create_contract;
select count(1) from proposal_approve_contract;
select count(1) from proposal_delete_contract;
select count(1) from set_account_id_contract;
select count(1) from trigger_smart_contract;
select count(1) from update_setting_contract;
select count(1) from exchange_create_contract;
select count(1) from exchange_inject_contract;
select count(1) from exchange_withdraw_contract;
select count(1) from exchange_transaction_contract;
select count(1) from update_energy_limit_contract;
select count(1) from account_permission_update_contract;
select count(1) from clear_abi_contract;
select count(1) from update_brokerage_contract;
select count(1) from shielded_transfer_contract;



drop table if exists err_trans_v1;
drop table if exists trans_v1;
drop table if exists vote_asset_contract_v1;
drop table if exists vote_asset_contract_vote_address_v1;
drop table if exists vote_witness_contract_v1;
drop table if exists vote_witness_contract_votes_v1;
drop table if exists proposal_create_contract_v1;
drop table if exists proposal_create_contract_parameters_v1;
drop table if exists create_smart_contract_v1;
drop table if exists create_smart_contract_abi_v1;
drop table if exists create_smart_contract_abi_inputs_v1;
drop table if exists create_smart_contract_abi_outputs_v1;
drop table if exists account_permission_update_contract_v1;
drop table if exists account_permission_update_contract_keys_v1;
drop table if exists account_permission_update_contract_actives_v1;
drop table if exists shielded_transfer_contract_v1;
drop table if exists market_sell_asset_contract_v1;
drop table if exists market_cancel_order_contract_v1;


insert into err_trans_v1 select * from ext_err_trans_v1;
insert into trans_v1 select * from ext_trans_v1;
insert into vote_asset_contract_v1 select * from ext_vote_asset_contract_v1;
insert into vote_asset_contract_vote_address_v1 select * from ext_vote_asset_contract_vote_address_v1;
insert into vote_witness_contract_v1 select * from ext_vote_witness_contract_v1;
insert into vote_witness_contract_votes_v1 select * from ext_vote_witness_contract_votes_v1;
insert into proposal_create_contract_v1 select * from ext_proposal_create_contract_v1;
insert into proposal_create_contract_parameters_v1 select * from ext_proposal_create_contract_parameters_v1;
insert into create_smart_contract_v1 select * from ext_create_smart_contract_v1;
insert into create_smart_contract_abi_v1 select * from ext_create_smart_contract_abi_v1;
insert into create_smart_contract_abi_inputs_v1 select * from ext_create_smart_contract_abi_inputs_v1;
insert into create_smart_contract_abi_outputs_v1 select * from ext_create_smart_contract_abi_outputs_v1;
insert into account_permission_update_contract_v1 select * from ext_account_permission_update_contract_v1;
insert into account_permission_update_contract_keys_v1 select * from ext_account_permission_update_contract_keys_v1;
insert into account_permission_update_contract_actives_v1 select * from ext_account_permission_update_contract_actives_v1;
insert into shielded_transfer_contract_v1 select * from ext_shielded_transfer_contract_v1;
insert into market_sell_asset_contract_v1 select * from ext_market_sell_asset_contract_v1;
insert into market_cancel_order_contract_v1 select * from ext_market_cancel_order_contract_v1;

select count(1) from err_trans_v1;
select count(1) from trans_v1;
select count(1) from vote_asset_contract_v1;
select count(1) from vote_asset_contract_vote_address_v1;
select count(1) from vote_witness_contract_v1;
select count(1) from vote_witness_contract_votes_v1;
select count(1) from proposal_create_contract_v1;
select count(1) from proposal_create_contract_parameters_v1;
select count(1) from create_smart_contract_v1;
select count(1) from create_smart_contract_abi_v1;
select count(1) from create_smart_contract_abi_inputs_v1;
select count(1) from create_smart_contract_abi_outputs_v1;
select count(1) from account_permission_update_contract_v1;
select count(1) from account_permission_update_contract_keys_v1;
select count(1) from account_permission_update_contract_actives_v1;
select count(1) from shielded_transfer_contract_v1;
select count(1) from market_sell_asset_contract_v1;
select count(1) from market_cancel_order_contract_v1;
